name: boxbox
description: Unofficial app for Formula 1 lovers.

publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

# Before releasing a new version, isInDebugMode must be set to false (main.dart#74).
version: 0.7.0+29 # Read above before bump.

environment:
  sdk: ">=2.19.0 <3.4.4"

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^3.6.0
  add_2_calendar: 2.2.4
  animations: ^2.0.8
  # awesome_notifications: ^0.7.4+1
  better_player:
    git:
      url: https://github.com/tintran-dev/betterplayer.git
      ref: master
  cached_network_image: ^3.3.0
  carousel_slider: ^4.1.1
  connectivity_plus: ^4.0.2
  dotted_line: ^3.2.2
  flutter_cache_manager: ^3.3.0
  flutter_inappwebview: ^6.0.0-beta.31
  flutter_localizations:
    sdk: flutter
  flutter_map: ^4.0.0
  flutter_markdown: ^0.6.10
  flutter_swiper_view: ^1.1.8
  flutter_timer_countdown: ^1.0.3
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.2.1
  geojson_vi: ^2.0.7
  hidable: ^1.0.6
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  html: ^0.15.4
  http: ^0.13.6
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.18.0
  latlong2: ^0.8.1
  loading_indicator: ^3.0.3
  map_controller_plus: # fork using null-safety
    git:
      url: https://github.com/TesteurManiak/map_controller_plus.git
      ref: master
  marquee: ^2.2.0
  package_info_plus: ^3.0.3
  receive_sharing_intent: # bumped Gradle to 7.4.2
    git:
      url: https://github.com/Nahrawene-ben-hmida/receive_sharing_intent.git
      ref: '6ad8f582d7bc7e2fd5a258399e7dbe8c39245d32' 
  share_plus: ^6.3.1
  # signalr_flutter: ^0.2.0 # uses (non-foss?) .jar
  sliding_up_panel: ^2.0.0+1
  story_view: # Updated packages with custom features. Origninally: https://github.com/blackmann/story_view
    path: ./story_view
  syncfusion_flutter_pdfviewer: 21.2.5
  timeago: ^3.5.0
  url_launcher: ^6.1.11
  video_player: ^2.7.2
  webfeed: # fork using null-safety
    git:
      url: https://github.com/marcjoha/webfeed.git
      ref: master
  #workmanager: ^0.5.1
  youtube_explode_dart: ^1.12.4

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.18.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  fonts:
    - family: Formula1
      fonts:
        - asset: assets/fonts/Formula1-Regular.ttf
        - asset: assets/fonts/Formula1-Black.ttf
          weight: 900
        - asset: assets/fonts/Formula1-Bold.ttf
          weight: 600
        - asset: assets/fonts/Formula1-Wide.ttf
          weight: 700

    - family: Titilium
      fonts:
        - asset : assets/fonts/TitilliumWeb-Regular.ttf
        - asset: assets/fonts/TitilliumWeb-Bold.ttf
          weight: 500

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
