name: boxbox
description: Unofficial app for Formula 1 lovers.

publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.2.0+6

environment:
  sdk: ">=2.12.0 <3.4.4"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.0
  carousel_slider: ^4.1.1
  chewie: ^1.3.4
  connectivity_plus: ^2.3.8
  dotted_line: ^3.1.0
  flutter_cache_manager: ^3.3.0
  flutter_localizations:
    sdk: flutter 
  flutter_map: ^0.14.0
  flutter_markdown: ^0.6.10
  flutter_timer_countdown: ^1.0.3
  font_awesome_flutter: ^10.1.0
  geojson_vi: ^2.0.7
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  html: ^0.15.0
  http: ^0.13.0
  intl: ^0.17.0
  latlong2: ^0.8.1
  loading_indicator: ^3.0.3
  map_controller: # fork using null-safety
    git:
      url: https://github.com/mpinkard/map_controller.git
      ref: null_safety
  marquee: ^2.2.0
  package_info_plus: ^1.4.3+1
  receive_sharing_intent: ^1.4.5
  share_plus: ^4.4.0
  sliding_up_panel: ^2.0.0+1
  syncfusion_flutter_pdfviewer: ^20.3.49
  text_divider: ^1.0.0
  timeago: ^3.3.0
  url_launcher: ^6.0.13
  video_player: ^2.4.5
  webview_flutter: ^3.0.4
  youtube_explode_dart: ^1.10.10+2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  fonts:
    - family: Formula1
      fonts:
        - asset: assets/fonts/Formula1-Regular.ttf
        - asset: assets/fonts/Formula1-Black.ttf
          weight: 900
        - asset: assets/fonts/Formula1-Bold.ttf
          weight: 600
        - asset: assets/fonts/Formula1-Wide.ttf
          weight: 700

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages